def fun(name):
    return name[-1]
print(fun("pratik"))
# fun(9) gives error

   